colorscheme base16
set global indentwidth 2

hook global WinCreate .* %{
    addhl number_lines -hlcursor -relative
    addhl show_matching
}

#set global termcmd 'st -e sh -c'

map -docstring "Comment the current line" global user c %{: comment-line<ret>}
map -docstring "Comment the current selection" global user C %{: comment-block<ret>}
map -docstring "Open local kakrc"  global user e %{: e ~/.config/kak/kakrc<ret>}
map -docstring "Format selection to 80 column width" global user f '|fmt -w80<ret>'
map -docstring "Open horizontal Tmux repl " global user H %{: tmux-repl-horizontal<ret>}
map -docstring "Split" global user n %{: x11-new<ret>}
map -docstring "Open fuzzy file finder in current directory" global user o %{: dmenu .<ret>}
map -docstring "Paste X11 clipboard after selection" global user p %{<a-!>xsel -b<ret>}
map -docstring "Paste X11 clipboard after selection" global user P %{!xsel -b<ret>}
map -docstring "Copy selection to X11 clipboard" global user \
  y %{<a-|>xsel -b<ret>;: echo "copied selection to X11 clipboard"<ret>}

