colorscheme desertex
set global indentwidth 2
set global termcmd "st sh -c"

hook global WinSetOption filetype=(kakrc|python) %{
  set buffer indentwidth 4
}

addhl global/ number-lines -hlcursor -relative
addhl global/ show-matching

# hook global WinCreate .* %{
#   auto-pairs-enable
# }

map -docstring "Open buffer via dmenu" global user b %{: dmenu-buffer .<ret>}
map -docstring "Comment the current line" global user C %{: comment-line<ret>}
map -docstring "Comment the current selection" global user c %{: comment-block<ret>}
map -docstring "Format selection to 80 column width" global user f '|fmt -w80<ret>'
map -docstring "Open horizontal Tmux repl " global user H %{: tmux-repl-horizontal<ret>}
map -docstring "Open file via dmenu" global user o %{: dmenu-open .<ret>}
map -docstring "Paste X11 clipboard after selection" global user p %{<a-!>xsel -bo<ret>}
map -docstring "Paste X11 clipboard after selection" global user P %{!xsel -bo<ret>}
map -docstring "Open X11 repl" global user R %{: my-x11-repl<ret>}
map -docstring "Create a new kak client for the current session" global user s %{: x11-new<ret>}
map -docstring "Open terminal window" global user t %{: x11-term<ret>}
map -docstring "Open ranger in new terminal window" global user T %{: x11-term ranger<ret>}
map -docstring "Copy selection to X11 clipboard" global user \
  y %{<a-|>xsel -b<ret>;: echo "copied selection to X11 clipboard"<ret>}

